- hosts: nn
  vars:
  - nn_dir: "/nn"
  - hadoop_software: "/root/hadoop-1.2.1-1.x86_64.rpm"
  - jdk_software: "/root/jdk-8u171-linux-x86.rpm"
  tasks:
  - name: "Copying JDK RPM file"
    copy:
      src: "{{jdk_software}}"
      dest: "/root/"
  - name: "Copying Hadoop RPM file"
    copy:
      src: "{{hadoop_software}}"
      dest: "/root/"
  - name: "Installing Java JDK"
    command: "rpm -ivh '{{jdk_software}}'"
    ignore_errors: yes
  - name: "Installing Hadoop"
    command: "rpm -ivh '{{hadoop_software}}' --force"
    ignore_errors: yes
  - name: "Creating directory nn for namenode"
    file:
      path: "nn_dir"
      state: directory
  - name: "Copying hdfs-site.xml configuration"
    template:
      src: "/root/nn_hdfs.xml"
      dest: "/etc/hadoop/hdfs-site.xml"
  - name: "Copying core-site.xml configuration"
    template:
      src: "/root/nn_core.xml"
      dest: "/etc/hadoop/core-site.xml"
  - name: "formatting the namenode"
    command: "hadoop namenode -format "
    ignore_errors: yes
  - name: "Starting the service"
    command: "hadoop-daemon.sh start namenode"
    ignore_errors: yes
  - name: "checking whether the process started or not"
    command: "jps"
    register: jps
  - debug:
      var:
        jps.stdout
      




